version: '3.7'
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        # image: wuuker/docker-airflow:2.2.5
        build:
            context: .
            dockerfile: Dockerfile.airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - PYTHONPATH=${PYTHONPATH}:/usr/local/airflow
        env_file:
            - db.env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./scraper:/usr/local/airflow/scraper
            - ./utils:/usr/local/airflow/utils
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
